{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agile-poker.fullname" . }}-db
  labels:
    {{- include "agile-poker.labels" . | nindent 4 }}
type: Opaque
data:
  connection-string: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username (.Values.postgresql.auth.password | b64enc | b64dec) (include "agile-poker.fullname" .) .Values.postgresql.auth.database | b64enc }}
{{- end }}
---
{{- if .Values.secrets.jiraApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agile-poker.fullname" . }}-secrets
  labels:
    {{- include "agile-poker.labels" . | nindent 4 }}
type: Opaque
stringData:
  jira-api-token: {{ .Values.secrets.jiraApiToken }}
{{- end }}
