/**
 * Runtime configuration loaded from window.__RUNTIME_CONFIG__
 * This is populated by config.js which is generated by the Kubernetes init script
 * Falls back to environment variables if runtime config is not available
 */

interface RuntimeConfig {
  apiUrl: string;
  logLevel: string;
  jiraEnabled: boolean;
}

declare global {
  interface Window {
    __RUNTIME_CONFIG__?: {
      REACT_APP_API_URL?: string;
      REACT_APP_LOG_LEVEL?: string;
      REACT_APP_JIRA_ENABLED?: string;
    };
  }
}

function getConfig(): RuntimeConfig {
  // Try to get runtime config from window object (set by config.js)
  if (typeof window !== 'undefined' && window.__RUNTIME_CONFIG__) {
    return {
      apiUrl: window.__RUNTIME_CONFIG__.REACT_APP_API_URL || process.env.REACT_APP_API_URL || 'http://localhost:8000/api',
      logLevel: window.__RUNTIME_CONFIG__.REACT_APP_LOG_LEVEL || process.env.REACT_APP_LOG_LEVEL || 'info',
      jiraEnabled: (window.__RUNTIME_CONFIG__.REACT_APP_JIRA_ENABLED || process.env.REACT_APP_JIRA_ENABLED || 'false').toLowerCase() === 'true',
    };
  }

  // Fallback to build-time environment variables
  return {
    apiUrl: process.env.REACT_APP_API_URL || 'http://localhost:8000/api',
    logLevel: process.env.REACT_APP_LOG_LEVEL || 'info',
    jiraEnabled: (process.env.REACT_APP_JIRA_ENABLED || 'false').toLowerCase() === 'true',
  };
}

export const config = getConfig();

export default config;
